### ISSUE TITLE
Collision detection

### ISSUE THREAD

**Issue by WomboCombo53** [INF23F13/DHBW-S1-Projekt#7]
Es muss noch erkannt werden, wenn die geschossene Bullet einen Gegner trifft. Der Gegner (Idee: wird zuerst rot als Animation) darf dann nicht mehr sichtbar sein.

**Comment by WomboCombo53** [comment]
plus Summierung der Punkte des Targets auf die Punkte des Spielers

**Comment by T0rstenGeh1** [comment]
Delete hit target. create new targets runtime ++
